# Generated by Django 5.0.3 on 2024-03-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False, verbose_name='id_client')),
                ('name', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False, verbose_name='id_country')),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.AutoField(primary_key=True, serialize=False, verbose_name='id_package')),
                ('package_name', models.CharField(max_length=150)),
                ('current_package_price_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='PackagePromotion',
            fields=[
                ('id_package_promotion', models.AutoField(primary_key=True, serialize=False, verbose_name='id_package_promotion')),
                ('discount_code', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'package_promotion',
            },
        ),
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id_post_code', models.AutoField(primary_key=True, serialize=False, verbose_name='id_post_code')),
                ('post_code', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'post_code',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False, verbose_name='id_service')),
                ('service_name', models.CharField(max_length=150)),
                ('current_service_price_money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServicePromotion',
            fields=[
                ('id_service_promotion', models.AutoField(primary_key=True, serialize=False, verbose_name='id_service_promotion')),
                ('discount_code', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'service_promotion',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id_service_type', models.AutoField(primary_key=True, serialize=False, verbose_name='id_service_type')),
                ('service_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id_client_package', models.AutoField(primary_key=True, serialize=False, verbose_name='id_client_package')),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.package')),
            ],
            options={
                'db_table': 'clientpackage',
            },
        ),
        migrations.CreateModel(
            name='ClientPackageLoyalty',
            fields=[
                ('id_client_package_loyalty', models.AutoField(primary_key=True, serialize=False, verbose_name='id_client_package_loyalty')),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('client_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientpackage')),
            ],
            options={
                'db_table': 'client_package_loyalty',
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id_client_service', models.AutoField(primary_key=True, serialize=False, verbose_name='id_client_service')),
                ('service_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.service')),
            ],
            options={
                'db_table': 'client_service',
            },
        ),
        migrations.CreateModel(
            name='ClientServiceLoyalty',
            fields=[
                ('id_client_service_loyalty', models.AutoField(primary_key=True, serialize=False, verbose_name='id_client_service_loyalty')),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientservice')),
            ],
            options={
                'db_table': 'client_service_loyalty',
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id_client_type', models.AutoField(primary_key=True, serialize=False, verbose_name='id_client_type')),
                ('type_name', models.CharField(max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'client_type',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False, verbose_name='id_city')),
                ('city_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='InvoicePackage',
            fields=[
                ('id_invoice_package', models.AutoField(primary_key=True, serialize=False, verbose_name='id_invoice_package')),
                ('final_package_price_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientpackage')),
            ],
            options={
                'db_table': 'invoice_package',
            },
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id_invoice_service', models.AutoField(primary_key=True, serialize=False, verbose_name='id_invoice_service')),
                ('final_service_price_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientservice')),
            ],
            options={
                'db_table': 'invoice_service',
            },
        ),
        migrations.CreateModel(
            name='PackagePromotionPackage',
            fields=[
                ('id_package_promotion_package', models.AutoField(primary_key=True, serialize=False, verbose_name='id_package_promotion_package')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.package')),
                ('package_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.packagepromotion')),
            ],
            options={
                'db_table': ' package_promotion_package',
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id_package_service', models.AutoField(primary_key=True, serialize=False, verbose_name='id_package_service')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.service')),
            ],
            options={
                'db_table': 'package_service',
            },
        ),
        migrations.CreateModel(
            name='ServicePromotionService',
            fields=[
                ('id_service_promotion_service', models.AutoField(primary_key=True, serialize=False, verbose_name='id_service_promotion_service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.service')),
                ('service_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicepromotion')),
            ],
            options={
                'db_table': 'service_promotion_service',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicetype'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id_street', models.AutoField(primary_key=True, serialize=False, verbose_name='id_street')),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.city')),
            ],
            options={
                'db_table': 'street',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False, verbose_name='id_address')),
                ('door_number', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.postcode')),
                ('id_street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.street')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
